# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: israelmorales
      MONGO_INITDB_ROOT_PASSWORD: Mora150784.

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9081:9081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: israelmorales
      ME_CONFIG_MONGODB_ADMINPASSWORD: Mora150784.
      ME_CONFIG_MONGODB_URL: mongodb://israelmorales:Mora150784.@mongo:27017/